CREATE TABLE IF NOT EXISTS USER(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL UNIQUE,
    USERNAME VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL,
    DATE_CREATED DATE NOT NULL
);
